#docker-compose.yaml
version: '3'
services:
  express-api:
    image: razzaksr/express-crud:latest
    ports:
      - "1234:1234"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
# #docker-compose.yaml
# version: '3'
# services:
#   express-api:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "1234:1234"
#     depends_on:
#       - mongo
#   mongo:
#     image: mongo
#     ports:
#       - "27017:27017"